version: '3'

services:
  web:
    restart: always
    build: web
    expose:
      - "8000"
    links:
      - postgres:postgres
    volumes:
      - web-static:/usr/src/app/static
    env_file: .env
    command: /usr/local/bin/gunicorn core.wsgi:application -w 2 -b :8000

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - web-static:/usr/src/app/static
    links:
      - web:web

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: "postgres"



volumes:
  web-static:
  pgdata:
